# Весь код выполняется за ~15 секунд

In [2]:
# Внимание!!! Важно, что бы файлы с данными и исполняемый файл находились в одной папке, 
# тогда пути к тестовым и тренировочным наборам будут содержать только имена файлов.
# 
# В пути к тренировочным и тестовым данным запрежается использовать абсалютную адресацию, 
# то есть адресацию, в которой присутствуют имена папок. Путь должен содержать только имя файла.
#
# Напоминание: под моделью машинного обучения понимаются все действия с исходными данными, 
# которые необходимо произвести, что бы сопоставить признаки целевому значению.

### Область работы 1 (библиотеки)

In [4]:
# Данный блок в области 1 выполняется преподавателем
# 
# данный блок предназначен только для подключения необходимых библиотек
# запрещается подключать библиотеки в других блоках
#
# установка дополнительных библиотек размещается прямо здесь (обязательно закоментированы)
#
# pip install

In [5]:
import numpy as np
import pandas as pd
from IPython.display import display
from sklearn.metrics import fbeta_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

### Область работы 2 (выполнение лучшей модели)

In [7]:
# Данный блок(и) в области 2 выполняется преподавателем
#
# В области находится одна, единственная, итоговая модель машинного обучения с однозначными, 
# зафиксированными параметрами
#
# В данной области категорически запрещается искать, выбирать, улучшать, оптимизировать, 
# тюниговать и т.д. модель машинного обучения

In [8]:
# Путь к тренировочному набору
path_train = 'train.csv' 
path_y = 'train_Y.csv'
# Путь к тестовому набору
path_test  = 'test.csv' 

In [9]:
X_df = pd.read_csv(path_train)
y_df = pd.read_csv(path_y)
df_test = pd.read_csv(path_test)

df = X_df.join(y_df, how='outer')
df = df.drop_duplicates()

X = df.drop('Diabetes_binary', axis=1)
y = df['Diabetes_binary']

class_weights = {0: 1, 1: 2.9}
sample_weight = np.array([class_weights[i] for i in y])

In [10]:
# Блок предсказания с использованием тестового набора (все три модели)
gb = GradientBoostingClassifier(n_estimators=300, max_depth=4)
gb.fit(X, y, sample_weight=sample_weight)

GradientBoostingClassifier(max_depth=4, n_estimators=300)

In [11]:
rf = RandomForestClassifier(n_estimators=1000, n_jobs = -1, criterion= 'gini', max_features='sqrt', max_depth=10, min_samples_split=9)
rf.fit(X, y, sample_weight=sample_weight)

RandomForestClassifier(max_depth=10, min_samples_split=9, n_estimators=1000,
                       n_jobs=-1)

In [12]:
# Вектора предсказанных значений  RandomForestClassifier или ExtraTreesClassifier
y_predict_RF = rf.predict(df_test)

In [13]:
# Вектора предсказанных значений  GradientBoostingClassifier или HistGradientBoostingClassifier
y_predict_GB = gb.predict(df_test)

In [14]:
# Вектора предсказанных значений  финальной модели
y_predict_final = gb.predict(df_test)

In [15]:
y_predict_RF

array([1., 1., 1., ..., 0., 1., 1.])

In [16]:
y_predict_final

array([1., 1., 1., ..., 0., 1., 1.])

In [17]:
y_predict_GB

array([1., 1., 1., ..., 0., 1., 1.])

In [18]:
print(len(y_predict_final))
print(len(y_predict_GB))
print(len(y_predict_RF))
print(df_test.shape)

23329
23329
23329
(23329, 21)
